image: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - SET PATH=%PATH%

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

environment:
  Appveyor: true
  
#services:
#  - mssql2012sp1  

nuget:
  disable_publish_on_pr: true

build_script:  
  - ps: .\build.ps1 -CreatePackages $true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg